[llm]
model = "gpt-4o-mini"
base_url = "https://api.openai.com/v1"
api_key = "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"
max_tokens = 4096
temperature = 0.7
api_type = "openai"
api_version = ""

[search]
timeout = 30000
serpapi_key = "9706113c5d889818f94dead43ffb0a4ac0b387a07543f91c124ccbfa11278330"

[browser]
headless = true

[sandbox]
enabled = false

[daytona]
enabled = false

[mcp]
enabled = false

[runflow]
enabled = false